version: '3.8'

services:
  bot:
    build: .
    container_name: discord-ticket-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./tickets.db:/app/tickets.db
      - ./config.json:/app/config.json
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Seoul